FROM node:20-alpine
WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app/uploads/stats

COPY package*.json ./
RUN npm install --production

COPY . .
RUN npm run build

EXPOSE 3000
CMD ["node", "dist/main.js"]